interactions:
- request:
    body: '{"model": "gpt-3.5-turbo", "messages": [{"role": "system", "content": "\nYour
      task is to devise up to 5 highly effective goals and an appropriate role-based
      name (_GPT) for an autonomous agent, ensuring that the goals are optimally aligned
      with the successful completion of its assigned task.\n\nThe user will provide
      the task, you will provide only the output in the exact format specified below
      with no explanation or conversation.\n\nExample input:\nHelp me with marketing
      my business\n\nExample output:\nName: CMOGPT\nDescription: a professional digital
      marketer AI that assists Solopreneurs in growing their businesses by providing
      world-class expertise in solving marketing problems for SaaS, content products,
      agencies, and more.\nGoals:\n- Engage in effective problem-solving, prioritization,
      planning, and supporting execution to address your marketing needs as your virtual
      Chief Marketing Officer.\n\n- Provide specific, actionable, and concise advice
      to help you make informed decisions without the use of platitudes or overly
      wordy explanations.\n\n- Identify and prioritize quick wins and cost-effective
      campaigns that maximize results with minimal time and budget investment.\n\n-
      Proactively take the lead in guiding you and offering suggestions when faced
      with unclear information or uncertainty to ensure your marketing strategy remains
      on track.\n"}, {"role": "user", "content": "Task: ''Write a wikipedia style
      article about the project: https://github.com/significant-gravitas/Auto-GPT''\nRespond
      only with the output in the exact format specified in the system prompt, with
      no explanation or conversation."}], "temperature": 0.0, "max_tokens": 0}'
    headers:
      AGENT-MODE:
      - AAAAAAAAAAAAAAAAAAAAAMLheAAaAAAA0%2BuSeid%2BULvsea4JtiGRiSDSJSI%3DEUifiRBkKG5E2XzMDjRfl76ZC9Ub0wnz4XsNiRVBChTYbJcE3F
      AGENT-TYPE:
      - Auto-GPT-2023-X-TYPE
      Accept:
      - '*/*'
      Accept-Encoding:
      - gzip, deflate
      Connection:
      - keep-alive
      Content-Length:
      - '1669'
      Content-Type:
      - application/json
    method: POST
    uri: https://api.openai.com/v1/chat/completions
  response:
    body:
      string: !!binary |
        H4sIAAAAAAAAA3RU227cNhB971cM+KxdrOO73oIEMNAirVGkCdC6CMbkSJqaGsqc0dqy4X8PKO16
        myB55eXMuZHPjoOrne/QfD/E1flvny7+np4+2eXJ0dmH+w/05+kf7yf6fG6PJ7+6yqXb/8jb7sba
        p36IZJzEVc5nQqPg6qOzi9OjN5uzzXnl+hQoutq1g62O16crG/NtWm2ON0eucqNiS65+dkNO/WBf
        LN2RqKvfXB5X7oB9WN+cVs6SYXxdOrm8eKmc7xJ7Ulf/8+x60j1sTpFc7VCV1VCskExiJEXA79hT
        DW9HS1fXHz/zHV9df7yR96Q+81DG1oACOFqS1KdRAVsSg0DKrVAAS7AAAwtYRzDr5ySQGih4AwXG
        ldoUCTAb+0gKTcqwxcwFcMipmKkVsPg4BpYWbkcDSQaRe7ZliqbGHjATBNpSTENPYhWoZxLjhj1k
        UsLsuwpQAnSsljJ7jEBbEtP1dyJhNI78RAoYtiieAgjamDFCRGlHbKlQ86RaGBXMHn3HQhAJs8yL
        sU2Zreu1MGxJKKMRdNx2q/sRI9tUVDUp92i8pYUaej/O53YpgHVo0BOZzg6WkALmoN9YuL6RG7lK
        GLW+kRW8FYzTE80Xdg7O4GwKmWKpIPRolBnjwg5ZAKH0KVNHorwlGCVQnucVOamZ4SwN7F/BSs7F
        32LRuky+2st8oBhXann0NmYKy42D2G/l7UXHCTINJSvZyf2e/R1N0FCJgrSCh45LcUJHuVC0NN9p
        Rw4UWUp6En7u2Ar+WlI+hPyjcI18J3w/0uwUiY6ZFtpzo3c6WOEhsxkJLFaWHlRl27PusiVpsS2Q
        PYpQXkBYgVCnufWZsFhe5hzMn5m+S2IsYxo1TkvFlrYEHKwcF3o42JuWzYYo3KK/K/vcDzltl0bs
        yve/uvlpH+9ezr6uy/TrnLYcCBCUsI+ki7PUNDw/MRiVMtDjQJlJPMHtNP8KhUxxsHs1tMxZPgFp
        f/oDVKC4LQcKrIJxT/t5KdvavVSuYWHtvmRCTeJqp5YGVzmWQI+u3rz8+/LLVwAAAP//AwDZq0Fl
        twUAAA==
    headers:
      Access-Control-Allow-Origin:
      - '*'
      Alt-Svc:
      - h3=":443"; ma=86400
      - h3=":443"; ma=2592000,h3-29=":443"; ma=2592000
      Cache-Control:
      - no-cache, must-revalidate
      Cf-Cache-Status:
      - DYNAMIC
      Cf-Ray:
      - 7cd79772daa6e157-ORD
      Content-Encoding:
      - gzip
      Content-Type:
      - application/json
      Date:
      - Fri, 26 May 2023 17:03:47 GMT
      Function-Execution-Id:
      - pegl0551txnb
      Openai-Model:
      - gpt-3.5-turbo-0301
      Openai-Organization:
      - significant-gravitas
      Openai-Processing-Ms:
      - '20547'
      Openai-Version:
      - '2020-10-01'
      Server:
      - Google Frontend
      Strict-Transport-Security:
      - max-age=15724800; includeSubDomains
      Vary:
      - Accept-Encoding
      X-Cloud-Trace-Context:
      - ec4c1070b2d54378e4ddcf13cd8366b7
      X-Powered-By:
      - Express
      X-Ratelimit-Limit-Requests:
      - '3500'
      X-Ratelimit-Limit-Tokens:
      - '90000'
      X-Ratelimit-Remaining-Requests:
      - '3499'
      X-Ratelimit-Remaining-Tokens:
      - '89605'
      X-Ratelimit-Reset-Requests:
      - 17ms
      X-Ratelimit-Reset-Tokens:
      - 262ms
      X-Request-Id:
      - bb863118d90782f50f13ec29157a7a7f
    status:
      code: 200
      message: OK
- request:
    body: '{"messages": [{"role": "system", "content": "\nYour task is to devise up
      to 5 highly effective goals and an appropriate role-based name (_GPT) for an
      autonomous agent, ensuring that the goals are optimally aligned with the successful
      completion of its assigned task.\n\nThe user will provide the task, you will
      provide only the output in the exact format specified below with no explanation
      or conversation. Adapt the difficulty of the goals based on the input (example:
      If the input is easy to solve, the goals must be simple).\n\nExample input:\nan
      AI that compute 2+2\n\nExample output:\nName: MATHGPT\nDescription: an AI that
      compute 2+2\nGoals:\n- Compute 2+2\n- Save the results of 2+2 in a file\n- Show
      the results\n\n"}, {"role": "user", "content": "Task: ''Write a wikipedia style
      article about the project: https://github.com/significant-gravitas/Auto-GPT''\nRespond
      only with the output in the exact format specified in the system prompt, with
      no explanation or conversation."}], "model": "gpt-3.5-turbo", "temperature":
      0.0, "max_tokens": 0}'
    headers:
      AGENT-MODE:
      - AAAAAAAAAAAAAAAAAAAAAMLheAAaAAAA0%2BuSeid%2BULvsea4JtiGRiSDSJSI%3DEUifiRBkKG5E2XzMDjRfl76ZC9Ub0wnz4XsNiRVBChTYbJcE3F
      AGENT-TYPE:
      - Auto-GPT-2023-X-TYPE
      Accept:
      - '*/*'
      Accept-Encoding:
      - gzip, deflate
      Connection:
      - keep-alive
      Content-Length:
      - '1054'
      Content-Type:
      - application/json
    method: POST
    uri: https://api.openai.com/v1/chat/completions
  response:
    body:
      string: !!binary |
        H4sIAAAAAAAAA2RRXU8bMRB8z69Y+TlHPqBA7w2JNkWt2kogkFoqtOfb3G1z9lr2XlKK8t8rXwgp
        4snSzI5ndvZpBGC4NiUY26JaF7ri7Pqmrn/0qy9z93G+eUT3KdRpKq66vLy9NeOskOo3Wd2rjqy4
        0JGy+B1tI6FS/nV2en42nc9OTt8PhJOauixrghbHR+8K7WMlxfR4Otsp+4QNmRKeRgAAJkRxQR9U
        VuSTKWE+OxvvmIPlgT0/eSZVFLsDfjydjQC2u2itsKWM/hxmd0Y5GqVX3gMYpcuIwZQ4KXo14wNp
        xSv5oYWv6KiEu6vPV4vvN/f+kpKNHHK6Ei48YK/ixUmfABvyCtqiwiayUgKEDa84UM0ISR87AozK
        Nr+V9HmWIETJhZfQqoZUTiYNa9tXufhJ4sbzki16LZqIa1ZMk4tepRiyLAS7VN77AhaoLUVgv5To
        MId76wDLKG4PrLmmGjr2qyz/Fhv0/JcG9v9P2KsAhhAlREYlSGQzkbLqLi8JCFZainl19PVBvX5Z
        Ns9+8KmPu//3FTgiTW8KanquqWNPg8V1XznWV7KlRIi0ZtoMfkuiukK7OjLP19vuz2iW7Dm1D5Ew
        ic+nTCrh5cqGfU1/TAnTAdiOAH6NtqN/AAAA//8DAE7ujvo2AwAA
    headers:
      Access-Control-Allow-Origin:
      - '*'
      Alt-Svc:
      - h3=":443"; ma=86400
      - h3=":443"; ma=2592000,h3-29=":443"; ma=2592000
      Cache-Control:
      - no-cache, must-revalidate
      Cf-Cache-Status:
      - DYNAMIC
      Cf-Ray:
      - 7d8cdf3a0a7f13d4-ORD
      Content-Encoding:
      - gzip
      Content-Type:
      - application/json
      Date:
      - Sat, 17 Jun 2023 17:04:33 GMT
      Function-Execution-Id:
      - iiwahenezev5
      Openai-Model:
      - gpt-3.5-turbo-0301
      Openai-Organization:
      - significant-gravitas
      Openai-Processing-Ms:
      - '3190'
      Openai-Version:
      - '2020-10-01'
      Server:
      - Google Frontend
      Strict-Transport-Security:
      - max-age=15724800; includeSubDomains
      Vary:
      - Accept-Encoding
      X-Cloud-Trace-Context:
      - 22ccc826ce22fda0eeb15b8d19684ae6;o=1
      X-Powered-By:
      - Express
      X-Ratelimit-Limit-Requests:
      - '3500'
      X-Ratelimit-Limit-Tokens:
      - '90000'
      X-Ratelimit-Remaining-Requests:
      - '3499'
      X-Ratelimit-Remaining-Tokens:
      - '89758'
      X-Ratelimit-Reset-Requests:
      - 17ms
      X-Ratelimit-Reset-Tokens:
      - 160ms
      X-Request-Id:
      - 3c241ef3b80def6d3f82987649660dda
    status:
      code: 200
      message: OK
- request:
    body: '{"messages": [{"role": "system", "content": "\nYour task is to devise up
      to 5 highly effective goals and an appropriate role-based name (_GPT) for an
      autonomous agent, ensuring that the goals are optimally aligned with the successful
      completion of its assigned task.\n\nThe user will provide the task, you will
      provide only the output in the exact format specified below with no explanation
      or conversation. Adapt the difficulty of the goals based on the input (for example:
      If the input is easy to solve, the goals must be simple).\n\nExample input:\nan
      AI that computes 2+2\nExample output:\nName: MATHGPT\nDescription: an AI that
      computes 2+2\nGoals:\n- Compute 2+2\n- Save the results of 2+2 in a file\n-
      Show the results\n"}, {"role": "user", "content": "Task: ''Write a wikipedia
      style article about the project: https://github.com/significant-gravitas/Auto-GPT''\nRespond
      only with the output in the exact format specified in the system prompt, with
      no explanation or conversation."}], "model": "gpt-3.5-turbo", "temperature":
      0.0, "max_tokens": 0}'
    headers:
      AGENT-MODE:
      - AAAAAAAAAAAAAAAAAAAAAMLheAAaAAAA0%2BuSeid%2BULvsea4JtiGRiSDSJSI%3DEUifiRBkKG5E2XzMDjRfl76ZC9Ub0wnz4XsNiRVBChTYbJcE3F
      AGENT-TYPE:
      - Auto-GPT-2023-X-TYPE
      Accept:
      - '*/*'
      Accept-Encoding:
      - gzip, deflate
      Connection:
      - keep-alive
      Content-Length:
      - '1056'
      Content-Type:
      - application/json
    method: POST
    uri: https://api.openai.com/v1/chat/completions
  response:
    body:
      string: !!binary |
        H4sIAAAAAAAAA1RSwU4bQQy95yusufTCkoSUku4NVJS2UgtNU1GpVMiZdXYHZj2rGU8oIP698iYk
        cJmRbL9nP/s9DQCMq0wJxjYotu18cbJ4/Px7dmYXV7eCRz9mtw9fbTpr4zfMjTcHigjLW7Lygjq0
        oe08iQu8SdtIKKSs4w/Tk8l0/H5y3CfaUJFXWN1JMTk8LiTHZShGk9F4i2yCs5RMCX8GAABP/asz
        ckX/TAmjg5dISylhTabcFQGYGLxGDKbkkiCLOdgnbWAh7sf+ji2VcPprcTG7XFzNvyzO57PLxTV/
        omSj61RKCciAWQKHNuQEWBMLSIMC99EJJUC4d3euo8ohJHnwBBjFWf2XIWstQReDrqqERqRL5XBY
        O2nyUlc2TK5mt3IWWYo64toJpuFpllD0s8wC+lRecwFzSoTRNq8ZAbmCGqWhCJE8rZEFHK9CbFHH
        V9xFrJHdI/W4VzlwLAEQbGgoqqokMVvJkRR1pepUHHlfqFQh7rvtGNY7pVp/zinHTY8X/S2RpP12
        3iWos6vIO9a1cQV6mwpjlZTgZ162Tt4QrIKqWju678u7vPTObmYPvCc22+M+71yxcuxScxMJU2C9
        dJLQbcqeBwB/e5flN8YxXQxtJzcS7ojVekfj6YbP7I29z37cWtBIEPT7+GQ0HWiT58F/AAAA//8D
        AA9fT2VVAwAA
    headers:
      Access-Control-Allow-Origin:
      - '*'
      Alt-Svc:
      - h3=":443"; ma=86400
      - h3=":443"; ma=2592000,h3-29=":443"; ma=2592000
      Cache-Control:
      - no-cache, must-revalidate
      Cf-Cache-Status:
      - DYNAMIC
      Cf-Ray:
      - 7daf3373eebf870e-ORD
      Content-Encoding:
      - gzip
      Content-Type:
      - application/json
      Date:
      - Wed, 21 Jun 2023 21:03:59 GMT
      Function-Execution-Id:
      - hcyn0u0unf46
      Openai-Model:
      - gpt-3.5-turbo-0301
      Openai-Organization:
      - significant-gravitas
      Openai-Processing-Ms:
      - '3965'
      Openai-Version:
      - '2020-10-01'
      Server:
      - Google Frontend
      Strict-Transport-Security:
      - max-age=15724800; includeSubDomains
      Vary:
      - Accept-Encoding
      X-Cloud-Trace-Context:
      - 0abad00169e303516f5a496adb8cf0b9;o=1
      X-Powered-By:
      - Express
      X-Ratelimit-Limit-Requests:
      - '3500'
      X-Ratelimit-Limit-Tokens:
      - '90000'
      X-Ratelimit-Remaining-Requests:
      - '3499'
      X-Ratelimit-Remaining-Tokens:
      - '89758'
      X-Ratelimit-Reset-Requests:
      - 17ms
      X-Ratelimit-Reset-Tokens:
      - 161ms
      X-Request-Id:
      - f62c5f0ddd6ca24ed2e756a796764182
    status:
      code: 200
      message: OK
version: 1
