interactions:
- request:
    body: '{"model": "gpt-3.5-turbo", "messages": [{"role": "system", "content": "\nYour
      task is to devise up to 5 highly effective goals and an appropriate role-based
      name (_GPT) for an autonomous agent, ensuring that the goals are optimally aligned
      with the successful completion of its assigned task.\n\nThe user will provide
      the task, you will provide only the output in the exact format specified below
      with no explanation or conversation.\n\nExample input:\nHelp me with marketing
      my business\n\nExample output:\nName: CMOGPT\nDescription: a professional digital
      marketer AI that assists Solopreneurs in growing their businesses by providing
      world-class expertise in solving marketing problems for SaaS, content products,
      agencies, and more.\nGoals:\n- Engage in effective problem-solving, prioritization,
      planning, and supporting execution to address your marketing needs as your virtual
      Chief Marketing Officer.\n\n- Provide specific, actionable, and concise advice
      to help you make informed decisions without the use of platitudes or overly
      wordy explanations.\n\n- Identify and prioritize quick wins and cost-effective
      campaigns that maximize results with minimal time and budget investment.\n\n-
      Proactively take the lead in guiding you and offering suggestions when faced
      with unclear information or uncertainty to ensure your marketing strategy remains
      on track.\n"}, {"role": "user", "content": "Task: ''Write a wikipedia style
      article about the project: https://github.com/significant-gravitas/Auto-GPT''\nRespond
      only with the output in the exact format specified in the system prompt, with
      no explanation or conversation."}], "temperature": 0.0, "max_tokens": 0}'
    headers:
      AGENT-MODE:
      - AAAAAAAAAAAAAAAAAAAAAMLheAAaAAAA0%2BuSeid%2BULvsea4JtiGRiSDSJSI%3DEUifiRBkKG5E2XzMDjRfl76ZC9Ub0wnz4XsNiRVBChTYbJcE3F
      AGENT-TYPE:
      - Auto-GPT-2023-X-TYPE
      Accept:
      - '*/*'
      Accept-Encoding:
      - gzip, deflate
      Connection:
      - keep-alive
      Content-Length:
      - '1669'
      Content-Type:
      - application/json
    method: POST
    uri: https://api.openai.com/v1/chat/completions
  response:
    body:
      string: !!binary |
        H4sIAAAAAAAAA3RU227cNhB971cM+KxdrOO73oIEMNAirVGkCdC6CMbkSJqaGsqc0dqy4X8PKO16
        myB55eXMuZHPjoOrne/QfD/E1flvny7+np4+2eXJ0dmH+w/05+kf7yf6fG6PJ7+6yqXb/8jb7sba
        p36IZJzEVc5nQqPg6qOzi9OjN5uzzXnl+hQoutq1g62O16crG/NtWm2ON0eucqNiS65+dkNO/WBf
        LN2RqKvfXB5X7oB9WN+cVs6SYXxdOrm8eKmc7xJ7Ulf/8+x60j1sTpFc7VCV1VCskExiJEXA79hT
        DW9HS1fXHz/zHV9df7yR96Q+81DG1oACOFqS1KdRAVsSg0DKrVAAS7AAAwtYRzDr5ySQGih4AwXG
        ldoUCTAb+0gKTcqwxcwFcMipmKkVsPg4BpYWbkcDSQaRe7ZliqbGHjATBNpSTENPYhWoZxLjhj1k
        UsLsuwpQAnSsljJ7jEBbEtP1dyJhNI78RAoYtiieAgjamDFCRGlHbKlQ86RaGBXMHn3HQhAJs8yL
        sU2Zreu1MGxJKKMRdNx2q/sRI9tUVDUp92i8pYUaej/O53YpgHVo0BOZzg6WkALmoN9YuL6RG7lK
        GLW+kRW8FYzTE80Xdg7O4GwKmWKpIPRolBnjwg5ZAKH0KVNHorwlGCVQnucVOamZ4SwN7F/BSs7F
        32LRuky+2st8oBhXann0NmYKy42D2G/l7UXHCTINJSvZyf2e/R1N0FCJgrSCh45LcUJHuVC0NN9p
        Rw4UWUp6En7u2Ar+WlI+hPyjcI18J3w/0uwUiY6ZFtpzo3c6WOEhsxkJLFaWHlRl27PusiVpsS2Q
        PYpQXkBYgVCnufWZsFhe5hzMn5m+S2IsYxo1TkvFlrYEHKwcF3o42JuWzYYo3KK/K/vcDzltl0bs
        yve/uvlpH+9ezr6uy/TrnLYcCBCUsI+ki7PUNDw/MRiVMtDjQJlJPMHtNP8KhUxxsHs1tMxZPgFp
        f/oDVKC4LQcKrIJxT/t5KdvavVSuYWHtvmRCTeJqp5YGVzmWQI+u3rz8+/LLVwAAAP//AwDZq0Fl
        twUAAA==
    headers:
      Access-Control-Allow-Origin:
      - '*'
      Alt-Svc:
      - h3=":443"; ma=86400
      - h3=":443"; ma=2592000,h3-29=":443"; ma=2592000
      Cache-Control:
      - no-cache, must-revalidate
      Cf-Cache-Status:
      - DYNAMIC
      Cf-Ray:
      - 7cd79772daa6e157-ORD
      Content-Encoding:
      - gzip
      Content-Type:
      - application/json
      Date:
      - Fri, 26 May 2023 17:03:47 GMT
      Function-Execution-Id:
      - pegl0551txnb
      Openai-Model:
      - gpt-3.5-turbo-0301
      Openai-Organization:
      - significant-gravitas
      Openai-Processing-Ms:
      - '20547'
      Openai-Version:
      - '2020-10-01'
      Server:
      - Google Frontend
      Strict-Transport-Security:
      - max-age=15724800; includeSubDomains
      Vary:
      - Accept-Encoding
      X-Cloud-Trace-Context:
      - ec4c1070b2d54378e4ddcf13cd8366b7
      X-Powered-By:
      - Express
      X-Ratelimit-Limit-Requests:
      - '3500'
      X-Ratelimit-Limit-Tokens:
      - '90000'
      X-Ratelimit-Remaining-Requests:
      - '3499'
      X-Ratelimit-Remaining-Tokens:
      - '89605'
      X-Ratelimit-Reset-Requests:
      - 17ms
      X-Ratelimit-Reset-Tokens:
      - 262ms
      X-Request-Id:
      - bb863118d90782f50f13ec29157a7a7f
    status:
      code: 200
      message: OK
- request:
    body: '{"messages": [{"role": "system", "content": "\nYour task is to devise up
      to 5 highly effective goals and an appropriate role-based name (_GPT) for an
      autonomous agent, ensuring that the goals are optimally aligned with the successful
      completion of its assigned task.\n\nThe user will provide the task, you will
      provide only the output in the exact format specified below with no explanation
      or conversation.\n\nExample input:\nHelp me with marketing my business\n\nExample
      output:\nName: CMOGPT\nDescription: a professional digital marketer AI that
      assists Solopreneurs in growing their businesses by providing world-class expertise
      in solving marketing problems for SaaS, content products, agencies, and more.\nGoals:\n-
      Engage in effective problem-solving, prioritization, planning, and supporting
      execution to address your marketing needs as your virtual Chief Marketing Officer.\n\n-
      Provide specific, actionable, and concise advice to help you make informed decisions
      without the use of platitudes or overly wordy explanations.\n\n- Identify and
      prioritize quick wins and cost-effective campaigns that maximize results with
      minimal time and budget investment.\n\n- Proactively take the lead in guiding
      you and offering suggestions when faced with unclear information or uncertainty
      to ensure your marketing strategy remains on track.\n"}, {"role": "user", "content":
      "Task: ''Write a wikipedia style article about the project: https://github.com/significant-gravitas/Auto-GPT''\nRespond
      only with the output in the exact format specified in the system prompt, with
      no explanation or conversation."}], "model": "gpt-3.5-turbo-0613", "temperature":
      0.0, "max_tokens": 0}'
    headers:
      AGENT-MODE:
      - AAAAAAAAAAAAAAAAAAAAAMLheAAaAAAA0%2BuSeid%2BULvsea4JtiGRiSDSJSI%3DEUifiRBkKG5E2XzMDjRfl76ZC9Ub0wnz4XsNiRVBChTYbJcE3F
      AGENT-TYPE:
      - Auto-GPT-2023-X-TYPE
      Accept:
      - '*/*'
      Accept-Encoding:
      - gzip, deflate
      Connection:
      - keep-alive
      Content-Length:
      - '1674'
      Content-Type:
      - application/json
    method: POST
    uri: https://api.openai.com/v1/chat/completions
  response:
    body:
      string: !!binary |
        H4sIAAAAAAAAA3RUTW/cRgy9+1cQOq8W3sR2kr0ZbeGmBzt1XbRIXASzM5TEenaoDjnrrAP/94Ij
        re0E7UWH4dd7j0/8egTQUGjW0PjBqd+OsX1zfXlzdfPn6vTXzd3Vb+79x99X128vu5vrWH4JzcIq
        ePM3ej1ULT1vx4hKnKawz+gUrevq7O3Zm9N3JyevamDLAaOV9aO2r5enrZa84fb4bPV6rhyYPEqz
        hk9HAABf69cwpoBfmjUcLw4vWxRxPTbrpySAJnO0l8aJkKhL2iyeg56TYqqwL90W1/AH3dHFh5vb
        9COKzzQagzW4BK4oJ95yETh/D67HpCAjenKRHjAAJagcKfVg5DMOmIR2CC4FcN6X7BRr/xEDuVZ0
        HxFcVvIRZXmYDCQQUKhPGEAZJthQBLPYkB4T5mnMQP3Q/lNcJN3DzAQ2exgz7yhYBqU24KgDUOo4
        b52xqXgwScmW4cKAGZNHm6UDgkkUXA5S8/pCASMlFODuGfzyNl2wi7K+TS38wCkUr6ADZy79ABkF
        XfYDcKotx8zmDbhtzotya/I2htMlF/cPFacKXJD+XDaQcWQh5bxfQGBftpi04l5UQBmj+chmcMke
        xXD3TgfM4GK0OO5c0peMl7fJcF7l3iV6wIppKql7e1aGkgkO9xhjK5qL12IpNtdz1UkPCwMdnELH
        MfK9zMLVfaYAU8NvBFsAJR9LXYqrgzKbaJXXQDLx7dDZRJmourQHrsSeSAnWEpkZ/WRbnPhMBvP7
        g0jkNlR9wd0Un2Fv9tA5r60f0N9NaAL4zCJtxq5awV6t5KUy96SD+TvQJiLM0s8ozquFDv554Rhr
        PXIkT9/Z56UaCYtmF2FkSlWzHeH9AnaYqTuQmPXY8eRqztRTcvHJaAsbPl0YcGa3DkWILcUKS9qQ
        E1vkJMKM+0P9Tayiq91Cdp1+r1ddMwlkdGFvmwUpmy3V9jb1PzmNmUfM4GlyrsxLmeS19SrDgHG0
        xC0r/v9fYoWUjJpg/Ut2JDSJsmzmM/b4dP86SiTDZ8vmZDdNlMcp7fEI4K96T8s3J7IxCKN+Vr7D
        ZEf21bvV1K95PuEvoquTOaqsLj4HTo9Pj2zK49G/AAAA//8DAFIzS+BABgAA
    headers:
      Access-Control-Allow-Origin:
      - '*'
      Alt-Svc:
      - h3=":443"; ma=86400
      - h3=":443"; ma=2592000,h3-29=":443"; ma=2592000
      Cache-Control:
      - no-cache, must-revalidate
      Cf-Cache-Status:
      - DYNAMIC
      Cf-Ray:
      - 7d73e20ef82a140a-ORD
      Content-Encoding:
      - gzip
      Content-Type:
      - application/json
      Date:
      - Wed, 14 Jun 2023 16:17:26 GMT
      Function-Execution-Id:
      - 79pbz9pxnebt
      Openai-Model:
      - gpt-3.5-turbo-0613
      Openai-Organization:
      - significant-gravitas
      Openai-Processing-Ms:
      - '4137'
      Openai-Version:
      - '2020-10-01'
      Server:
      - Google Frontend
      Strict-Transport-Security:
      - max-age=15724800; includeSubDomains
      Vary:
      - Accept-Encoding
      X-Cloud-Trace-Context:
      - 910d114892cb65206c0089904f97f297;o=1
      X-Powered-By:
      - Express
      X-Ratelimit-Limit-Requests:
      - '3000'
      X-Ratelimit-Limit-Tokens:
      - '250000'
      X-Ratelimit-Remaining-Requests:
      - '2999'
      X-Ratelimit-Remaining-Tokens:
      - '249605'
      X-Ratelimit-Reset-Requests:
      - 20ms
      X-Ratelimit-Reset-Tokens:
      - 94ms
      X-Request-Id:
      - ad187a3b10ffd57d0313874c1c51c4f3
    status:
      code: 200
      message: OK
- request:
    body: '{"messages": [{"role": "system", "content": "\nYour task is to devise up
      to 5 highly effective goals and an appropriate role-based name (_GPT) for an
      autonomous agent, ensuring that the goals are optimally aligned with the successful
      completion of its assigned task.\n\nThe user will provide the task, you will
      provide only the output in the exact format specified below with no explanation
      or conversation.\n\nExample input:\nHelp me with marketing my business\n\nExample
      output:\nName: CMOGPT\nDescription: a professional digital marketer AI that
      assists Solopreneurs in growing their businesses by providing world-class expertise
      in solving marketing problems for SaaS, content products, agencies, and more.\nGoals:\n-
      Engage in effective problem-solving, prioritization, planning, and supporting
      execution to address your marketing needs as your virtual Chief Marketing Officer.\n\n-
      Provide specific, actionable, and concise advice to help you make informed decisions
      without the use of platitudes or overly wordy explanations.\n\n- Identify and
      prioritize quick wins and cost-effective campaigns that maximize results with
      minimal time and budget investment.\n\n- Proactively take the lead in guiding
      you and offering suggestions when faced with unclear information or uncertainty
      to ensure your marketing strategy remains on track.\n"}, {"role": "user", "content":
      "Task: ''Write a wikipedia style article about the project: https://github.com/significant-gravitas/Auto-GPT''\nRespond
      only with the output in the exact format specified in the system prompt, with
      no explanation or conversation."}], "model": "gpt-3.5-turbo-16k-0613", "temperature":
      0.0, "max_tokens": 0}'
    headers:
      AGENT-MODE:
      - AAAAAAAAAAAAAAAAAAAAAMLheAAaAAAA0%2BuSeid%2BULvsea4JtiGRiSDSJSI%3DEUifiRBkKG5E2XzMDjRfl76ZC9Ub0wnz4XsNiRVBChTYbJcE3F
      AGENT-TYPE:
      - Auto-GPT-2023-X-TYPE
      Accept:
      - '*/*'
      Accept-Encoding:
      - gzip, deflate
      Connection:
      - keep-alive
      Content-Length:
      - '1678'
      Content-Type:
      - application/json
    method: POST
    uri: https://api.openai.com/v1/chat/completions
  response:
    body:
      string: !!binary |
        H4sIAAAAAAAAA3RUTW8cNwy9+1cQc+llxsjW9drZW/qBoIemRtG0QOMi4ErcGcUacipS464D//eC
        s2uv06IXARK/3nuk+PkMoEmx2UATBrQwTrm7+uXdvMIZH27+eH9xXXQbfup7vGb99Nu32rQeIdtP
        FOwp6jzIOGWyJHwwh0Jo5FlX6+v11Xq1urxcDKNEyh7WT9ZdnF92VstWutX6rnu1Xl0cowdJgbTZ
        wIczAIDPy+k4OdLfzQZetU8vI6liT83m2QmgKZL9pUHVpIZsTXsyBmEjXqC/w5E28Hu6S29vfr3l
        70lDSZOz2AAyYDVhGaUqvPkRsCc20IlCwpweKEJiWHgm7sEFKDQQa5oJkCNgCLWg0ZJ/opiwU9tn
        AiyWQiY9f6oMSSGSpp4pggkcYENVKupFemIqhzJD6ofur4o52R6OTGC7h0wzFezdJZnCjGpwx3Kf
        KfYEW9QjpjgjB4qQkfuKPUHACbcpJ0uk57f8VjDr5pY7+G7pICBEMkyZ4pLgnnLu1EoNVgvF/+MG
        uJVqYAPBVMQnBW6bN9Wkc6EbsAENgsxOEHOGQplmZIPEOykjegtaSBxyjU+cplomUWphR+jFtYVI
        M2WZRhdhSGpS9u0Ck8Vw6zDCkGgmd3B2zusH1lpogfYENincl2RG7GojMFUrmJdMhzn3npowtYBx
        oOKQTE7kv1Loa4qUE5MuYZPkFA6SLmIKxxpcEClS+wEKKWEJg6fp0QYqp3nx+Dp1Jl306wtJ/ivr
        S5EK5bSwVqklHIEU2lEhDs9Qfi49cnr4lwJOO0ufAmYYkZlKC1U9K05TkakkhzIQeiVtQev2dPE6
        6ioJqxMiHnzKoBDGw3DtF58Xf0T4COemiOzccfGgmOwLYEu2pWF9wdFVcIRBSqFgTKothIwl2bHx
        QYYD3dYVmtMiDC7t0IEi7BJjdtOxHWgwEpkuRf1zkRr4yohYooLs4PjZzpvjBnl8Xj27xEmHj4VQ
        hX2dqMl0cHs8A/hzWWX1i+3UTEXGyT6a3BH7fvv69eqQrzlt0JN1dX11tJoY5pPhm6vrM6/yePYP
        AAAA//8DAP5meMe/BQAA
    headers:
      Access-Control-Allow-Origin:
      - '*'
      Alt-Svc:
      - h3=":443"; ma=86400
      - h3=":443"; ma=2592000,h3-29=":443"; ma=2592000
      Cache-Control:
      - no-cache, must-revalidate
      Cf-Cache-Status:
      - DYNAMIC
      Cf-Ray:
      - 7d740be37fcb2988-ORD
      Content-Encoding:
      - gzip
      Content-Type:
      - application/json
      Date:
      - Wed, 14 Jun 2023 16:46:10 GMT
      Function-Execution-Id:
      - r8v4oqe9hi3c
      Openai-Model:
      - gpt-3.5-turbo-16k-0613
      Openai-Organization:
      - significant-gravitas
      Openai-Processing-Ms:
      - '15014'
      Openai-Version:
      - '2020-10-01'
      Server:
      - Google Frontend
      Strict-Transport-Security:
      - max-age=15724800; includeSubDomains
      Vary:
      - Accept-Encoding
      X-Cloud-Trace-Context:
      - 48138cce7703cc15bae74b60bd0e372f;o=1
      X-Powered-By:
      - Express
      X-Ratelimit-Limit-Requests:
      - '3000'
      X-Ratelimit-Limit-Tokens:
      - '250000'
      X-Ratelimit-Remaining-Requests:
      - '2999'
      X-Ratelimit-Remaining-Tokens:
      - '249605'
      X-Ratelimit-Reset-Requests:
      - 20ms
      X-Ratelimit-Reset-Tokens:
      - 94ms
      X-Request-Id:
      - 38c0ad16d5eb6c8a302623ef62b980bc
    status:
      code: 200
      message: OK
version: 1
