interactions:
- request:
    body: '{"model": "gpt-3.5-turbo", "messages": [{"role": "system", "content": "\nYour
      task is to devise up to 5 highly effective goals and an appropriate role-based
      name (_GPT) for an autonomous agent, ensuring that the goals are optimally aligned
      with the successful completion of its assigned task.\n\nThe user will provide
      the task, you will provide only the output in the exact format specified below
      with no explanation or conversation.\n\nExample input:\nHelp me with marketing
      my business\n\nExample output:\nName: CMOGPT\nDescription: a professional digital
      marketer AI that assists Solopreneurs in growing their businesses by providing
      world-class expertise in solving marketing problems for SaaS, content products,
      agencies, and more.\nGoals:\n- Engage in effective problem-solving, prioritization,
      planning, and supporting execution to address your marketing needs as your virtual
      Chief Marketing Officer.\n\n- Provide specific, actionable, and concise advice
      to help you make informed decisions without the use of platitudes or overly
      wordy explanations.\n\n- Identify and prioritize quick wins and cost-effective
      campaigns that maximize results with minimal time and budget investment.\n\n-
      Proactively take the lead in guiding you and offering suggestions when faced
      with unclear information or uncertainty to ensure your marketing strategy remains
      on track.\n"}, {"role": "user", "content": "Task: ''T&GF\u00a3OIBECC()!*''\nRespond
      only with the output in the exact format specified in the system prompt, with
      no explanation or conversation."}], "temperature": 0.0, "max_tokens": 0}'
    headers:
      AGENT-MODE:
      - AAAAAAAAAAAAAAAAAAAAAMLheAAaAAAA0%2BuSeid%2BULvsea4JtiGRiSDSJSI%3DEUifiRBkKG5E2XzMDjRfl76ZC9Ub0wnz4XsNiRVBChTYbJcE3F
      AGENT-TYPE:
      - Auto-GPT-2023-X-TYPE
      Accept:
      - '*/*'
      Accept-Encoding:
      - gzip, deflate
      Connection:
      - keep-alive
      Content-Length:
      - '1590'
      Content-Type:
      - application/json
    method: POST
    uri: https://api.openai.com/v1/chat/completions
  response:
    body:
      string: !!binary |
        H4sIAAAAAAAAA0zOPW4CMRCG4T6nGE2TxqBlEWTxDVAo0iQFUYSMPbAG27OyZyEIcfcI8kPabzSP
        3jN6hxpta8TGLgyent+a2PbbaJt6GV75cFwcFrt2Ppst1xYV8npHVn4+hpZjF0g8J1RoMxkhh3o0
        bSajuprWlcLIjgJq3HYyGA8nA+nzmgfVuBqhwr6YLaE+Y5c5drIS3lMqqOumUni3/+0KhcWEv2Vc
        NReFtmVvqaB+P2Ok8qtmDoQaTSm+iElybeQklK7988cIhXM+KZiDNSmxQJf54B2BScC9dL3A0UvL
        vYABG8hkMMlBnxzlK+jMOhCIKfshvAQyhe4CHEzw7naEDWeIBMLwnQIn7m/yEC8KNz750q4ymcIJ
        NRbhDhX65OgTdXX5uDx8AQAA//8DANQ76GClAQAA
    headers:
      Access-Control-Allow-Origin:
      - '*'
      Alt-Svc:
      - h3=":443"; ma=86400
      - h3=":443"; ma=2592000,h3-29=":443"; ma=2592000
      Cache-Control:
      - no-cache, must-revalidate
      Cf-Cache-Status:
      - DYNAMIC
      Cf-Ray:
      - 7cd797c7b8172d19-ORD
      Content-Encoding:
      - gzip
      Content-Type:
      - application/json
      Date:
      - Fri, 26 May 2023 17:03:45 GMT
      Function-Execution-Id:
      - u75a1w60qkmd
      Openai-Model:
      - gpt-3.5-turbo-0301
      Openai-Organization:
      - significant-gravitas
      Openai-Processing-Ms:
      - '4635'
      Openai-Version:
      - '2020-10-01'
      Server:
      - Google Frontend
      Strict-Transport-Security:
      - max-age=15724800; includeSubDomains
      Vary:
      - Accept-Encoding
      X-Cloud-Trace-Context:
      - 6444596b1ff59b706e529742bac3a855;o=1
      X-Powered-By:
      - Express
      X-Ratelimit-Limit-Requests:
      - '3500'
      X-Ratelimit-Limit-Tokens:
      - '90000'
      X-Ratelimit-Remaining-Requests:
      - '3499'
      X-Ratelimit-Remaining-Tokens:
      - '89626'
      X-Ratelimit-Reset-Requests:
      - 17ms
      X-Ratelimit-Reset-Tokens:
      - 248ms
      X-Request-Id:
      - 8328aeaa91a9fdfa98e92438444f1258
    status:
      code: 200
      message: OK
- request:
    body: '{"messages": [{"role": "system", "content": "\nYour task is to devise up
      to 5 highly effective goals and an appropriate role-based name (_GPT) for an
      autonomous agent, ensuring that the goals are optimally aligned with the successful
      completion of its assigned task.\n\nThe user will provide the task, you will
      provide only the output in the exact format specified below with no explanation
      or conversation. Adapt the difficulty of the goals based on the input (example:
      If the input is easy to solve, the goals must be simple).\n\nExample input:\nan
      AI that compute 2+2\n\nExample output:\nName: MATHGPT\nDescription: an AI that
      compute 2+2\nGoals:\n- Compute 2+2\n- Save the results of 2+2 in a file\n- Show
      the results\n\n"}, {"role": "user", "content": "Task: ''T&GF\u00a3OIBECC()!*''\nRespond
      only with the output in the exact format specified in the system prompt, with
      no explanation or conversation."}], "model": "gpt-3.5-turbo", "temperature":
      0.0, "max_tokens": 0}'
    headers:
      AGENT-MODE:
      - AAAAAAAAAAAAAAAAAAAAAMLheAAaAAAA0%2BuSeid%2BULvsea4JtiGRiSDSJSI%3DEUifiRBkKG5E2XzMDjRfl76ZC9Ub0wnz4XsNiRVBChTYbJcE3F
      AGENT-TYPE:
      - Auto-GPT-2023-X-TYPE
      Accept:
      - '*/*'
      Accept-Encoding:
      - gzip, deflate
      Connection:
      - keep-alive
      Content-Length:
      - '975'
      Content-Type:
      - application/json
    method: POST
    uri: https://api.openai.com/v1/chat/completions
  response:
    body:
      string: !!binary |
        H4sIAAAAAAAAA2xS227TQBB991cM+0ApiqskLU3wI0kbVUJtRMNDRFA12R3HC/aMtbtuiap8DX/C
        l1Vrp00RvJ7LnKOjeUwAlDUqA6ULDLqqy3R0uzDV9uPD19nDkItiuSyvL+XisxRrWaLqRYesf5AO
        z64TLVVdUrDCHa0dYaB4dXA+HvWHg7PRuCUqMVRG26YO6enJhzQ0bi1p/7Q/6JyNxw2pDB4TAABV
        O6nqcBfkJ7FXGQz7Z72OOUQe2PPxngwSsHzlGg0TgF1XrRCrKaLfWm0XFKuR/yu7BZ2UEVHovfUB
        OajegdTCgbhd4RorymDyZTlf3MzmixVPyWtn69gvA2TAJghLJY0H3BAHCAUG0MhgSLttHQGCfQc4
        WrydXf75fXP16WIyeXf85v3RimeCpc9WnMKVIQ4237YW4tZuhaGiUIiBxpOJsum/hyN8i/fUYvtg
        Mi+xlgEht2Wrm1pfl7j9vzQK5k7urSFA0MK5NcSawGtxBLm41odaNw71FiR/fSf+yX7G3fOeKrds
        fXHnCL1w3NQHqV/mVpYN/VIZ9FtglwB8T3bJEwAAAP//AwAb9MKPvwIAAA==
    headers:
      Access-Control-Allow-Origin:
      - '*'
      Alt-Svc:
      - h3=":443"; ma=86400
      - h3=":443"; ma=2592000,h3-29=":443"; ma=2592000
      Cache-Control:
      - no-cache, must-revalidate
      Cf-Cache-Status:
      - DYNAMIC
      Cf-Ray:
      - 7d8cdf70df542c24-ORD
      Content-Encoding:
      - gzip
      Content-Type:
      - application/json
      Date:
      - Sat, 17 Jun 2023 17:04:41 GMT
      Function-Execution-Id:
      - g225bevm7rkj
      Openai-Model:
      - gpt-3.5-turbo-0301
      Openai-Organization:
      - significant-gravitas
      Openai-Processing-Ms:
      - '2686'
      Openai-Version:
      - '2020-10-01'
      Server:
      - Google Frontend
      Strict-Transport-Security:
      - max-age=15724800; includeSubDomains
      Vary:
      - Accept-Encoding
      X-Cloud-Trace-Context:
      - b98dc8e96868e5ab610d39557760de72
      X-Powered-By:
      - Express
      X-Ratelimit-Limit-Requests:
      - '3500'
      X-Ratelimit-Limit-Tokens:
      - '90000'
      X-Ratelimit-Remaining-Requests:
      - '3499'
      X-Ratelimit-Remaining-Tokens:
      - '89779'
      X-Ratelimit-Reset-Requests:
      - 17ms
      X-Ratelimit-Reset-Tokens:
      - 146ms
      X-Request-Id:
      - 6d42856448beab34605a037f742b41f3
    status:
      code: 200
      message: OK
version: 1
