interactions:
- request:
    body: '{"model": "gpt-3.5-turbo", "messages": [{"role": "system", "content": "\nYour
      task is to devise up to 5 highly effective goals and an appropriate role-based
      name (_GPT) for an autonomous agent, ensuring that the goals are optimally aligned
      with the successful completion of its assigned task.\n\nThe user will provide
      the task, you will provide only the output in the exact format specified below
      with no explanation or conversation.\n\nExample input:\nHelp me with marketing
      my business\n\nExample output:\nName: CMOGPT\nDescription: a professional digital
      marketer AI that assists Solopreneurs in growing their businesses by providing
      world-class expertise in solving marketing problems for SaaS, content products,
      agencies, and more.\nGoals:\n- Engage in effective problem-solving, prioritization,
      planning, and supporting execution to address your marketing needs as your virtual
      Chief Marketing Officer.\n\n- Provide specific, actionable, and concise advice
      to help you make informed decisions without the use of platitudes or overly
      wordy explanations.\n\n- Identify and prioritize quick wins and cost-effective
      campaigns that maximize results with minimal time and budget investment.\n\n-
      Proactively take the lead in guiding you and offering suggestions when faced
      with unclear information or uncertainty to ensure your marketing strategy remains
      on track.\n"}, {"role": "user", "content": "Task: ''T&GF\u00a3OIBECC()!*''\nRespond
      only with the output in the exact format specified in the system prompt, with
      no explanation or conversation."}], "temperature": 0.0, "max_tokens": 0}'
    headers:
      AGENT-MODE:
      - AAAAAAAAAAAAAAAAAAAAAMLheAAaAAAA0%2BuSeid%2BULvsea4JtiGRiSDSJSI%3DEUifiRBkKG5E2XzMDjRfl76ZC9Ub0wnz4XsNiRVBChTYbJcE3F
      AGENT-TYPE:
      - Auto-GPT-2023-X-TYPE
      Accept:
      - '*/*'
      Accept-Encoding:
      - gzip, deflate
      Connection:
      - keep-alive
      Content-Length:
      - '1590'
      Content-Type:
      - application/json
    method: POST
    uri: https://api.openai.com/v1/chat/completions
  response:
    body:
      string: !!binary |
        H4sIAAAAAAAAA0zOPW4CMRCG4T6nGE2TxqBlEWTxDVAo0iQFUYSMPbAG27OyZyEIcfcI8kPabzSP
        3jN6hxpta8TGLgyent+a2PbbaJt6GV75cFwcFrt2Ppst1xYV8npHVn4+hpZjF0g8J1RoMxkhh3o0
        bSajuprWlcLIjgJq3HYyGA8nA+nzmgfVuBqhwr6YLaE+Y5c5drIS3lMqqOumUni3/+0KhcWEv2Vc
        NReFtmVvqaB+P2Ok8qtmDoQaTSm+iElybeQklK7988cIhXM+KZiDNSmxQJf54B2BScC9dL3A0UvL
        vYABG8hkMMlBnxzlK+jMOhCIKfshvAQyhe4CHEzw7naEDWeIBMLwnQIn7m/yEC8KNz750q4ymcIJ
        NRbhDhX65OgTdXX5uDx8AQAA//8DANQ76GClAQAA
    headers:
      Access-Control-Allow-Origin:
      - '*'
      Alt-Svc:
      - h3=":443"; ma=86400
      - h3=":443"; ma=2592000,h3-29=":443"; ma=2592000
      Cache-Control:
      - no-cache, must-revalidate
      Cf-Cache-Status:
      - DYNAMIC
      Cf-Ray:
      - 7cd797c7b8172d19-ORD
      Content-Encoding:
      - gzip
      Content-Type:
      - application/json
      Date:
      - Fri, 26 May 2023 17:03:45 GMT
      Function-Execution-Id:
      - u75a1w60qkmd
      Openai-Model:
      - gpt-3.5-turbo-0301
      Openai-Organization:
      - significant-gravitas
      Openai-Processing-Ms:
      - '4635'
      Openai-Version:
      - '2020-10-01'
      Server:
      - Google Frontend
      Strict-Transport-Security:
      - max-age=15724800; includeSubDomains
      Vary:
      - Accept-Encoding
      X-Cloud-Trace-Context:
      - 6444596b1ff59b706e529742bac3a855;o=1
      X-Powered-By:
      - Express
      X-Ratelimit-Limit-Requests:
      - '3500'
      X-Ratelimit-Limit-Tokens:
      - '90000'
      X-Ratelimit-Remaining-Requests:
      - '3499'
      X-Ratelimit-Remaining-Tokens:
      - '89626'
      X-Ratelimit-Reset-Requests:
      - 17ms
      X-Ratelimit-Reset-Tokens:
      - 248ms
      X-Request-Id:
      - 8328aeaa91a9fdfa98e92438444f1258
    status:
      code: 200
      message: OK
- request:
    body: '{"messages": [{"role": "system", "content": "\nYour task is to devise up
      to 5 highly effective goals and an appropriate role-based name (_GPT) for an
      autonomous agent, ensuring that the goals are optimally aligned with the successful
      completion of its assigned task.\n\nThe user will provide the task, you will
      provide only the output in the exact format specified below with no explanation
      or conversation.\n\nExample input:\nHelp me with marketing my business\n\nExample
      output:\nName: CMOGPT\nDescription: a professional digital marketer AI that
      assists Solopreneurs in growing their businesses by providing world-class expertise
      in solving marketing problems for SaaS, content products, agencies, and more.\nGoals:\n-
      Engage in effective problem-solving, prioritization, planning, and supporting
      execution to address your marketing needs as your virtual Chief Marketing Officer.\n\n-
      Provide specific, actionable, and concise advice to help you make informed decisions
      without the use of platitudes or overly wordy explanations.\n\n- Identify and
      prioritize quick wins and cost-effective campaigns that maximize results with
      minimal time and budget investment.\n\n- Proactively take the lead in guiding
      you and offering suggestions when faced with unclear information or uncertainty
      to ensure your marketing strategy remains on track.\n"}, {"role": "user", "content":
      "Task: ''T&GF\u00a3OIBECC()!*''\nRespond only with the output in the exact format
      specified in the system prompt, with no explanation or conversation."}], "model":
      "gpt-3.5-turbo-0613", "temperature": 0.0, "max_tokens": 0}'
    headers:
      AGENT-MODE:
      - AAAAAAAAAAAAAAAAAAAAAMLheAAaAAAA0%2BuSeid%2BULvsea4JtiGRiSDSJSI%3DEUifiRBkKG5E2XzMDjRfl76ZC9Ub0wnz4XsNiRVBChTYbJcE3F
      AGENT-TYPE:
      - Auto-GPT-2023-X-TYPE
      Accept:
      - '*/*'
      Accept-Encoding:
      - gzip, deflate
      Connection:
      - keep-alive
      Content-Length:
      - '1595'
      Content-Type:
      - application/json
    method: POST
    uri: https://api.openai.com/v1/chat/completions
  response:
    body:
      string: !!binary |
        H4sIAAAAAAAAA5RUwW4cNwy971cQc/Yacez1OnsLWiBtD24apDm0LgKuhjvDWEOqEmfsTeB/L6iZ
        eBMgl1500BPfIx9JfVkBNNw2O2hCjxaGFNfbd7fv8dP0J93+1h82tw/jLy//uhk+/PGqbN9NzZlH
        6P4TBfsadR50SJGMVWY4ZEIjZ724vrnebl5dba4qMGhL0cO6ZOvL883axrzX9Yvri8slslcOVJod
        /L0CAPhST89RWnpsdvDi7OvNQKVgR83u+RFAkzX6TYOlcDEUa85OYFAxkpr2LQ60g9e//v7m7fs7
        +ZlKyJy8gB2gAI6mooOOBViMYuSOxADraT0azPwOQ9E4sXQwm/AIKes+0lAApQVNxgN/djxlDVQK
        FcCQtRSYMLNLtDogS4H9ESJNlLHz59hOKIFawNhpZusXxhYNAQXjsXABo9AL/ztSOb+TN4qx7O5k
        Da8d/0w1YJSWsnvRgvUEHU8kYFjuwRS4JTE+HCtUX8bjkqwXUQkOmocxojkd0OFAwXgir3t0x6BY
        RqPueF6VU4rH/528p7JYRd8aJS3wkLJO5MIcmCQcvzXd0/ZaqvZPKsYy6liiW4lZKgO2mMwVhB6A
        xcvBmriDoUfp5vZJy35dkyEpY6ZKP2ixOTmMp6LZ29gzTdRW7bdZJ24JguvOzCqBCwE9poiCM7Ue
        KuczDaaUFUNfIzKVMVrVP2DgyOamn/pXx8JdpMCFVdYD3rN0S+0x4l69E/DA1oNaT3ke2QKaoR8H
        b99jomwFHnoSEHKfMR9dcRk9gqAxLi0+DX+YZ2kO96p+1INmWbWn5x09sHDpP2bCouJ7V0zT/Oxp
        BfBP3fnxuzVuUtYh2UfTexL/CF5ub2a+5vTNnNCLy+2CmhrGE3B1sVm5ytPqPwAAAP//AwBd1VVb
        5AQAAA==
    headers:
      Access-Control-Allow-Origin:
      - '*'
      Alt-Svc:
      - h3=":443"; ma=86400
      - h3=":443"; ma=2592000,h3-29=":443"; ma=2592000
      Cache-Control:
      - no-cache, must-revalidate
      Cf-Cache-Status:
      - DYNAMIC
      Cf-Ray:
      - 7d73e25c6e31874b-ORD
      Content-Encoding:
      - gzip
      Content-Type:
      - application/json
      Date:
      - Wed, 14 Jun 2023 16:17:37 GMT
      Function-Execution-Id:
      - 79pb34yz6boe
      Openai-Model:
      - gpt-3.5-turbo-0613
      Openai-Organization:
      - significant-gravitas
      Openai-Processing-Ms:
      - '3193'
      Openai-Version:
      - '2020-10-01'
      Server:
      - Google Frontend
      Strict-Transport-Security:
      - max-age=15724800; includeSubDomains
      Vary:
      - Accept-Encoding
      X-Cloud-Trace-Context:
      - bf871cb058c4731bddcd7c2f78d8c8dc;o=1
      X-Powered-By:
      - Express
      X-Ratelimit-Limit-Requests:
      - '3000'
      X-Ratelimit-Limit-Tokens:
      - '250000'
      X-Ratelimit-Remaining-Requests:
      - '2999'
      X-Ratelimit-Remaining-Tokens:
      - '249626'
      X-Ratelimit-Reset-Requests:
      - 20ms
      X-Ratelimit-Reset-Tokens:
      - 89ms
      X-Request-Id:
      - aa4f32d9f4efab56c90fede02175532b
    status:
      code: 200
      message: OK
- request:
    body: '{"messages": [{"role": "system", "content": "\nYour task is to devise up
      to 5 highly effective goals and an appropriate role-based name (_GPT) for an
      autonomous agent, ensuring that the goals are optimally aligned with the successful
      completion of its assigned task.\n\nThe user will provide the task, you will
      provide only the output in the exact format specified below with no explanation
      or conversation.\n\nExample input:\nHelp me with marketing my business\n\nExample
      output:\nName: CMOGPT\nDescription: a professional digital marketer AI that
      assists Solopreneurs in growing their businesses by providing world-class expertise
      in solving marketing problems for SaaS, content products, agencies, and more.\nGoals:\n-
      Engage in effective problem-solving, prioritization, planning, and supporting
      execution to address your marketing needs as your virtual Chief Marketing Officer.\n\n-
      Provide specific, actionable, and concise advice to help you make informed decisions
      without the use of platitudes or overly wordy explanations.\n\n- Identify and
      prioritize quick wins and cost-effective campaigns that maximize results with
      minimal time and budget investment.\n\n- Proactively take the lead in guiding
      you and offering suggestions when faced with unclear information or uncertainty
      to ensure your marketing strategy remains on track.\n"}, {"role": "user", "content":
      "Task: ''T&GF\u00a3OIBECC()!*''\nRespond only with the output in the exact format
      specified in the system prompt, with no explanation or conversation."}], "model":
      "gpt-3.5-turbo-16k-0613", "temperature": 0.0, "max_tokens": 0}'
    headers:
      AGENT-MODE:
      - AAAAAAAAAAAAAAAAAAAAAMLheAAaAAAA0%2BuSeid%2BULvsea4JtiGRiSDSJSI%3DEUifiRBkKG5E2XzMDjRfl76ZC9Ub0wnz4XsNiRVBChTYbJcE3F
      AGENT-TYPE:
      - Auto-GPT-2023-X-TYPE
      Accept:
      - '*/*'
      Accept-Encoding:
      - gzip, deflate
      Connection:
      - keep-alive
      Content-Length:
      - '1599'
      Content-Type:
      - application/json
    method: POST
    uri: https://api.openai.com/v1/chat/completions
  response:
    body:
      string: !!binary |
        H4sIAAAAAAAAA5xUTW/jRgy9+1cQOsdG1LR24Nu2BRbtIbsoekjRLBb0DC0xGZHTGUqxs8h/L2ak
        xNtrLzrMI997/NK3FUDDvtlD43o0N8Sw3v1xN90/ur9+v3/MfH13355ud8/h+OlnHu9emquSoYdH
        cvaWtXE6xEDGKjPsEqFRYW23t9vdtm1vdxUY1FMoaV209c3mp7WN6aDrdvu0vt62N0t2r+woN3v4
        ewUA8K1+i0/xdGr2cH319jJQzthRs38PAmiShvLSYM6cDcWaqwvoVIykWr/Dgfbw4bdPHz//+SC/
        UnaJYyliDyiAo6nooGMGFqMQuCMxwPq1Hg1m/gJD1jCxdDA34gQx6SHQkAHFg0bjgV8KHpM6ypky
        oEuaM0yYuEh4HZAlw+EMgSZK2JVw9BOKIw8YOk1s/cI4oOtZCAJhkhJo5Hrhf0bKmwf5qBjy/kHW
        8EEwnF+o5oziKZV2eLCeoOOJBAzzE5gCexLj47lCNTKcF7+ljkpw1DSMAa3QAR2P5IwnKqWPpWmQ
        LaFRd95U5RjD+f/4L26WhtH37RIPPMSkExVtdkzizt+3vjgv5VT5X1SMZdQxh/OsUhnQY7SiIPQM
        LKUirN4L6HqUbh6ieC7P1QxJHhNV+kGzzeYwXOrmMsyeaSJftT8nndgTuKI7M6s4zgR0igEFZ2o9
        Vs53GowxKbq+ZiTKY7Cqf0THga30/TLCuhziwZPjzCrrAZ9YuqX2EPCgZRjwzNaDWk9pXty5kXSK
        lGb2ZdkInIawTPSy7m5eHZK+jPFtG9bv244RD8UcU940y429vh/nkYVz/zURZpVycNk0zmGvK4Av
        9djH/9xvE5MO0b6aPpGUP8APu9uZr7n8Yy5oe3OzoKaG4QL82LarovK6+hcAAP//AwDDSFEo4QQA
        AA==
    headers:
      Access-Control-Allow-Origin:
      - '*'
      Alt-Svc:
      - h3=":443"; ma=86400
      - h3=":443"; ma=2592000,h3-29=":443"; ma=2592000
      Cache-Control:
      - no-cache, must-revalidate
      Cf-Cache-Status:
      - DYNAMIC
      Cf-Ray:
      - 7d740ca7ef248108-ORD
      Content-Encoding:
      - gzip
      Content-Type:
      - application/json
      Date:
      - Wed, 14 Jun 2023 16:46:38 GMT
      Function-Execution-Id:
      - r8v4gjdg6kjp
      Openai-Model:
      - gpt-3.5-turbo-16k-0613
      Openai-Organization:
      - significant-gravitas
      Openai-Processing-Ms:
      - '12104'
      Openai-Version:
      - '2020-10-01'
      Server:
      - Google Frontend
      Strict-Transport-Security:
      - max-age=15724800; includeSubDomains
      Vary:
      - Accept-Encoding
      X-Cloud-Trace-Context:
      - 2cacb26796c2dc9c487afaf93a08a00a;o=1
      X-Powered-By:
      - Express
      X-Ratelimit-Limit-Requests:
      - '3000'
      X-Ratelimit-Limit-Tokens:
      - '250000'
      X-Ratelimit-Remaining-Requests:
      - '2999'
      X-Ratelimit-Remaining-Tokens:
      - '249626'
      X-Ratelimit-Reset-Requests:
      - 20ms
      X-Ratelimit-Reset-Tokens:
      - 89ms
      X-Request-Id:
      - cd9668d3410fed458c6d63fa40800e55
    status:
      code: 200
      message: OK
version: 1
