interactions:
- request:
    body: '{"model": "gpt-3.5-turbo", "messages": [{"role": "system", "content": "\nYour
      task is to devise up to 5 highly effective goals and an appropriate role-based
      name (_GPT) for an autonomous agent, ensuring that the goals are optimally aligned
      with the successful completion of its assigned task.\n\nThe user will provide
      the task, you will provide only the output in the exact format specified below
      with no explanation or conversation.\n\nExample input:\nHelp me with marketing
      my business\n\nExample output:\nName: CMOGPT\nDescription: a professional digital
      marketer AI that assists Solopreneurs in growing their businesses by providing
      world-class expertise in solving marketing problems for SaaS, content products,
      agencies, and more.\nGoals:\n- Engage in effective problem-solving, prioritization,
      planning, and supporting execution to address your marketing needs as your virtual
      Chief Marketing Officer.\n\n- Provide specific, actionable, and concise advice
      to help you make informed decisions without the use of platitudes or overly
      wordy explanations.\n\n- Identify and prioritize quick wins and cost-effective
      campaigns that maximize results with minimal time and budget investment.\n\n-
      Proactively take the lead in guiding you and offering suggestions when faced
      with unclear information or uncertainty to ensure your marketing strategy remains
      on track.\n"}, {"role": "user", "content": "Task: ''Help me create a rock opera
      about cybernetic giraffes''\nRespond only with the output in the exact format
      specified in the system prompt, with no explanation or conversation."}], "temperature":
      0.0, "max_tokens": 0}'
    headers:
      AGENT-MODE:
      - AAAAAAAAAAAAAAAAAAAAAMLheAAaAAAA0%2BuSeid%2BULvsea4JtiGRiSDSJSI%3DEUifiRBkKG5E2XzMDjRfl76ZC9Ub0wnz4XsNiRVBChTYbJcE3F
      AGENT-TYPE:
      - Auto-GPT-2023-X-TYPE
      Accept:
      - '*/*'
      Accept-Encoding:
      - gzip, deflate
      Connection:
      - keep-alive
      Content-Length:
      - '1623'
      Content-Type:
      - application/json
    method: POST
    uri: https://api.openai.com/v1/chat/completions
  response:
    body:
      string: !!binary |
        H4sIAAAAAAAAA3SUQW/cRgyF7/0VxJy1C69j165uToIkRZHGaIoeEhcBd0RJzI6GkyFn7Y3h/16M
        tI59SK8jDvm99zi6d9y51vkRzU8prC7++Ofy+tXh9cj7D3R1dv79/fXu9v2pvPz05tsn1zjZfiVv
        xxtrL1MKZCzRNc5nQqPOtZtfL883pyfnv100bpKOgmvdkGz1Yn2+spK3sjp5cbJxjSuKA7n23qUs
        U7IvJjuK6trTy7PGPfX+cb65vGiciWH4cXR2sXlonB+FPalrP9+7ifSxbZZArnWoymoYrUJKNIpV
        wJ84UQt/id99SG+v/76Jr0l95lQntoARrn6HWRLvCbxELaH2ABvRQBN5xsDfSYEjjBQSxwEwG6sp
        YOxgKsqeMSpsc/1mI3GGEvlbIdizskQFEwjc0/qJA1iX7j17DOEAHSkPkbpauyipE22kI51EkB6y
        +B1IoozaQMqy564OpbtE2WAo3GH0NINpSUlyFZKlDKMUm7tRNM70JDll8aS6volvBYO2N3EFryQE
        3EpGI7hlG+EgpXJ1tKcgCRBqahRCna0m+RA40mKZx2Qlky7DVKnySA/+sKUcydjDwBn7nhb/LGPU
        gFYdrpKr/GcyoZc8oa0r1tX/2jLRJBm3gcCPmNEbZW3Ao/nxACpx0GYeRnHAoUJ3jEGGcmS+5RBg
        R5QAS8eVWGcdvK+bDn2WCdSwminQc2QdZ6DrOQCCnqjbot8dfR8GUptzlwVV9pQxBFDLxVd35sKE
        vqJIP9c8k2wCFHUuAy8jac2p3uApobe+hCXwmbQaNDd4RJ/J3lFIc2oR9zzUHGuJkR9j3TfAunum
        dXjK0pWZ5LnvDXD0oXRLwjjQcUEbCDyMxnFYHFUp1de+r+2air78HwDBcgkH4GmiPCt4Yp4RPx73
        s1JyrBiT2IxRXxXmHdnxPf3cmwnveCpTbSv66Kmx35GBYiBdu4fGLWl9yYQq0bVOTZJrHMeO7lx7
        8vDvwy//AQAA//8DAJMll+IcBQAA
    headers:
      Access-Control-Allow-Origin:
      - '*'
      Alt-Svc:
      - h3=":443"; ma=86400
      - h3=":443"; ma=2592000,h3-29=":443"; ma=2592000
      Cache-Control:
      - no-cache, must-revalidate
      Cf-Cache-Status:
      - DYNAMIC
      Cf-Ray:
      - 7cd79738dd8022d0-ORD
      Content-Encoding:
      - gzip
      Content-Type:
      - application/json
      Date:
      - Fri, 26 May 2023 17:03:38 GMT
      Function-Execution-Id:
      - u75anm04ybm4
      Openai-Model:
      - gpt-3.5-turbo-0301
      Openai-Organization:
      - significant-gravitas
      Openai-Processing-Ms:
      - '20744'
      Openai-Version:
      - '2020-10-01'
      Server:
      - Google Frontend
      Strict-Transport-Security:
      - max-age=15724800; includeSubDomains
      Vary:
      - Accept-Encoding
      X-Cloud-Trace-Context:
      - c402bf3036960902e1be5293361e5c65;o=1
      X-Powered-By:
      - Express
      X-Ratelimit-Limit-Requests:
      - '3500'
      X-Ratelimit-Limit-Tokens:
      - '90000'
      X-Ratelimit-Remaining-Requests:
      - '3499'
      X-Ratelimit-Remaining-Tokens:
      - '89617'
      X-Ratelimit-Reset-Requests:
      - 17ms
      X-Ratelimit-Reset-Tokens:
      - 254ms
      X-Request-Id:
      - b44e6c90eb755e0bef60a3f2b20c1e10
    status:
      code: 200
      message: OK
- request:
    body: '{"messages": [{"role": "system", "content": "\nYour task is to devise up
      to 5 highly effective goals and an appropriate role-based name (_GPT) for an
      autonomous agent, ensuring that the goals are optimally aligned with the successful
      completion of its assigned task.\n\nThe user will provide the task, you will
      provide only the output in the exact format specified below with no explanation
      or conversation.\n\nExample input:\nHelp me with marketing my business\n\nExample
      output:\nName: CMOGPT\nDescription: a professional digital marketer AI that
      assists Solopreneurs in growing their businesses by providing world-class expertise
      in solving marketing problems for SaaS, content products, agencies, and more.\nGoals:\n-
      Engage in effective problem-solving, prioritization, planning, and supporting
      execution to address your marketing needs as your virtual Chief Marketing Officer.\n\n-
      Provide specific, actionable, and concise advice to help you make informed decisions
      without the use of platitudes or overly wordy explanations.\n\n- Identify and
      prioritize quick wins and cost-effective campaigns that maximize results with
      minimal time and budget investment.\n\n- Proactively take the lead in guiding
      you and offering suggestions when faced with unclear information or uncertainty
      to ensure your marketing strategy remains on track.\n"}, {"role": "user", "content":
      "Task: ''Help me create a rock opera about cybernetic giraffes''\nRespond only
      with the output in the exact format specified in the system prompt, with no
      explanation or conversation."}], "model": "gpt-3.5-turbo-0613", "temperature":
      0.0, "max_tokens": 0}'
    headers:
      AGENT-MODE:
      - AAAAAAAAAAAAAAAAAAAAAMLheAAaAAAA0%2BuSeid%2BULvsea4JtiGRiSDSJSI%3DEUifiRBkKG5E2XzMDjRfl76ZC9Ub0wnz4XsNiRVBChTYbJcE3F
      AGENT-TYPE:
      - Auto-GPT-2023-X-TYPE
      Accept:
      - '*/*'
      Accept-Encoding:
      - gzip, deflate
      Connection:
      - keep-alive
      Content-Length:
      - '1628'
      Content-Type:
      - application/json
    method: POST
    uri: https://api.openai.com/v1/chat/completions
  response:
    body:
      string: !!binary |
        H4sIAAAAAAAAA2xUTW/cRgy9+1cQOq+NOI4dd2+BC9g91DFSFz3URcAdcSXGI3I6pNZeB/7vwYyk
        2EZ7EYTh1+PjI78fADTcNmtoQo8ehhQPP365vv1T7ffLx6vry/7220X+fCHvnq6f8nl/1axKhG6+
        UfAl6ijokCI5q0zmkAmdStbjs/Ozj6e/fPhwXg2DthRLWJf88OTo9NDHvNHDd2fHJ3NkrxzImjX8
        fQAA8L1+C0Zp6bFZw7vV8jKQGXbUrH86ATRZY3lp0IzNUbxZvRiDipNU2Nc40Bq+fL65vLm9k1/J
        QuZUGlgDCrCI7tB5R1BbKT+ffgPv0cESBcbIT2TAAlMhlg4wO5sboLQwjMaBUarLlEI6GIX/Hak6
        BEzOu+k5a7gHTZTRjuAv9h4QWqIEo7SUSxdtcdMteE/QkeQpB0Iq1VVgqxnMNe+dYmTpVnNnwAY9
        ZQJX6Ckm2OsIm1yy7XXMsOMarltACPsNZSHnAB1n3G7pFbCSIPKWju7kUjHa+k4O4UJjxI1mdIKH
        Artkd4WWdhQ1lZw6pAnRBC+y0MRi0GHDQlZbokgDiVsB8gLDVgsQW9V+K5zKbCUeHnA/JSPpsCN7
        Q+ycGseWSUIBXiB/qtMq4cU4DWYiYKBBM24iQegxY3DKtipenJeGCkbAHGY4k43FqbizilUW5txv
        uSOxsUwNMoe+RvMwULYiLHpMlF+DvMm645agG7lFCdOwq5ez0aQo3FbpJH2gvB3j5DJogYEx7iGT
        qaA4mEpnC+eyo31F5z0NM2HzGtmirxfgK3joORJgNIUNlXqV/Vqgcs7SzZivFnWxQEvGnRT3HdtY
        vc1HqS+VOAq9aNRuToXtrrTZgjl2BEZuKwhqPg7L6FPWZMuw+0pKwao7yhgjIJn3Vbp1L3xQS1X3
        /+lphvvHmJJmXxAXn5S1Hescl4oTnf/HC0uIY13KLU/LaSN7Vc+OZKSKX3PLMm849YTZMM7tzIKq
        jGK+J582pGxSx0W5CuheZFVkXrSw6Hga9KQmdgMbQyCzo2a+cs8/z+OWha3/mglNpZw8c02T2/MB
        wD/13I5vLmhTmk7+1fWepNzg9+fvp3zNy4V/ZT05nq2ujvHFcHp8clCqPB/8AAAA//8DAH6YgRNf
        BgAA
    headers:
      Access-Control-Allow-Origin:
      - '*'
      Alt-Svc:
      - h3=":443"; ma=86400
      - h3=":443"; ma=2592000,h3-29=":443"; ma=2592000
      Cache-Control:
      - no-cache, must-revalidate
      Cf-Cache-Status:
      - DYNAMIC
      Cf-Ray:
      - 7d73e2367c842980-ORD
      Content-Encoding:
      - gzip
      Content-Type:
      - application/json
      Date:
      - Wed, 14 Jun 2023 16:17:32 GMT
      Function-Execution-Id:
      - 79pbk6gxgsun
      Openai-Model:
      - gpt-3.5-turbo-0613
      Openai-Organization:
      - significant-gravitas
      Openai-Processing-Ms:
      - '4088'
      Openai-Version:
      - '2020-10-01'
      Server:
      - Google Frontend
      Strict-Transport-Security:
      - max-age=15724800; includeSubDomains
      Vary:
      - Accept-Encoding
      X-Cloud-Trace-Context:
      - 7ccf8e4f44fd49fff20cc9144a261e38
      X-Powered-By:
      - Express
      X-Ratelimit-Limit-Requests:
      - '3000'
      X-Ratelimit-Limit-Tokens:
      - '250000'
      X-Ratelimit-Remaining-Requests:
      - '2999'
      X-Ratelimit-Remaining-Tokens:
      - '249618'
      X-Ratelimit-Reset-Requests:
      - 20ms
      X-Ratelimit-Reset-Tokens:
      - 91ms
      X-Request-Id:
      - 7bf29b89be7aa8bb48a4f95443cb1a71
    status:
      code: 200
      message: OK
version: 1
