interactions:
- request:
    body: '{"model": "gpt-3.5-turbo", "messages": [{"role": "system", "content": "\nYour
      task is to devise up to 5 highly effective goals and an appropriate role-based
      name (_GPT) for an autonomous agent, ensuring that the goals are optimally aligned
      with the successful completion of its assigned task.\n\nThe user will provide
      the task, you will provide only the output in the exact format specified below
      with no explanation or conversation.\n\nExample input:\nHelp me with marketing
      my business\n\nExample output:\nName: CMOGPT\nDescription: a professional digital
      marketer AI that assists Solopreneurs in growing their businesses by providing
      world-class expertise in solving marketing problems for SaaS, content products,
      agencies, and more.\nGoals:\n- Engage in effective problem-solving, prioritization,
      planning, and supporting execution to address your marketing needs as your virtual
      Chief Marketing Officer.\n\n- Provide specific, actionable, and concise advice
      to help you make informed decisions without the use of platitudes or overly
      wordy explanations.\n\n- Identify and prioritize quick wins and cost-effective
      campaigns that maximize results with minimal time and budget investment.\n\n-
      Proactively take the lead in guiding you and offering suggestions when faced
      with unclear information or uncertainty to ensure your marketing strategy remains
      on track.\n"}, {"role": "user", "content": "Task: ''Help me create a rock opera
      about cybernetic giraffes''\nRespond only with the output in the exact format
      specified in the system prompt, with no explanation or conversation."}], "temperature":
      0.0, "max_tokens": 0}'
    headers:
      AGENT-MODE:
      - AAAAAAAAAAAAAAAAAAAAAMLheAAaAAAA0%2BuSeid%2BULvsea4JtiGRiSDSJSI%3DEUifiRBkKG5E2XzMDjRfl76ZC9Ub0wnz4XsNiRVBChTYbJcE3F
      AGENT-TYPE:
      - Auto-GPT-2023-X-TYPE
      Accept:
      - '*/*'
      Accept-Encoding:
      - gzip, deflate
      Connection:
      - keep-alive
      Content-Length:
      - '1623'
      Content-Type:
      - application/json
    method: POST
    uri: https://api.openai.com/v1/chat/completions
  response:
    body:
      string: !!binary |
        H4sIAAAAAAAAA3SUQW/cRgyF7/0VxJy1C69j165uToIkRZHGaIoeEhcBd0RJzI6GkyFn7Y3h/16M
        tI59SK8jDvm99zi6d9y51vkRzU8prC7++Ofy+tXh9cj7D3R1dv79/fXu9v2pvPz05tsn1zjZfiVv
        xxtrL1MKZCzRNc5nQqPOtZtfL883pyfnv100bpKOgmvdkGz1Yn2+spK3sjp5cbJxjSuKA7n23qUs
        U7IvJjuK6trTy7PGPfX+cb65vGiciWH4cXR2sXlonB+FPalrP9+7ifSxbZZArnWoymoYrUJKNIpV
        wJ84UQt/id99SG+v/76Jr0l95lQntoARrn6HWRLvCbxELaH2ABvRQBN5xsDfSYEjjBQSxwEwG6sp
        YOxgKsqeMSpsc/1mI3GGEvlbIdizskQFEwjc0/qJA1iX7j17DOEAHSkPkbpauyipE22kI51EkB6y
        +B1IoozaQMqy564OpbtE2WAo3GH0NINpSUlyFZKlDKMUm7tRNM70JDll8aS6volvBYO2N3EFryQE
        3EpGI7hlG+EgpXJ1tKcgCRBqahRCna0m+RA40mKZx2Qlky7DVKnySA/+sKUcydjDwBn7nhb/LGPU
        gFYdrpKr/GcyoZc8oa0r1tX/2jLRJBm3gcCPmNEbZW3Ao/nxACpx0GYeRnHAoUJ3jEGGcmS+5RBg
        R5QAS8eVWGcdvK+bDn2WCdSwminQc2QdZ6DrOQCCnqjbot8dfR8GUptzlwVV9pQxBFDLxVd35sKE
        vqJIP9c8k2wCFHUuAy8jac2p3uApobe+hCXwmbQaNDd4RJ/J3lFIc2oR9zzUHGuJkR9j3TfAunum
        dXjK0pWZ5LnvDXD0oXRLwjjQcUEbCDyMxnFYHFUp1de+r+2air78HwDBcgkH4GmiPCt4Yp4RPx73
        s1JyrBiT2IxRXxXmHdnxPf3cmwnveCpTbSv66Kmx35GBYiBdu4fGLWl9yYQq0bVOTZJrHMeO7lx7
        8vDvwy//AQAA//8DAJMll+IcBQAA
    headers:
      Access-Control-Allow-Origin:
      - '*'
      Alt-Svc:
      - h3=":443"; ma=86400
      - h3=":443"; ma=2592000,h3-29=":443"; ma=2592000
      Cache-Control:
      - no-cache, must-revalidate
      Cf-Cache-Status:
      - DYNAMIC
      Cf-Ray:
      - 7cd79738dd8022d0-ORD
      Content-Encoding:
      - gzip
      Content-Type:
      - application/json
      Date:
      - Fri, 26 May 2023 17:03:38 GMT
      Function-Execution-Id:
      - u75anm04ybm4
      Openai-Model:
      - gpt-3.5-turbo-0301
      Openai-Organization:
      - significant-gravitas
      Openai-Processing-Ms:
      - '20744'
      Openai-Version:
      - '2020-10-01'
      Server:
      - Google Frontend
      Strict-Transport-Security:
      - max-age=15724800; includeSubDomains
      Vary:
      - Accept-Encoding
      X-Cloud-Trace-Context:
      - c402bf3036960902e1be5293361e5c65;o=1
      X-Powered-By:
      - Express
      X-Ratelimit-Limit-Requests:
      - '3500'
      X-Ratelimit-Limit-Tokens:
      - '90000'
      X-Ratelimit-Remaining-Requests:
      - '3499'
      X-Ratelimit-Remaining-Tokens:
      - '89617'
      X-Ratelimit-Reset-Requests:
      - 17ms
      X-Ratelimit-Reset-Tokens:
      - 254ms
      X-Request-Id:
      - b44e6c90eb755e0bef60a3f2b20c1e10
    status:
      code: 200
      message: OK
- request:
    body: '{"messages": [{"role": "system", "content": "\nYour task is to devise up
      to 5 highly effective goals and an appropriate role-based name (_GPT) for an
      autonomous agent, ensuring that the goals are optimally aligned with the successful
      completion of its assigned task.\n\nThe user will provide the task, you will
      provide only the output in the exact format specified below with no explanation
      or conversation. Adapt the difficulty of the goals based on the input (example:
      If the input is easy to solve, the goals must be simple).\n\nExample input:\nan
      AI that compute 2+2\n\nExample output:\nName: MATHGPT\nDescription: an AI that
      compute 2+2\nGoals:\n- Compute 2+2\n- Save the results of 2+2 in a file\n- Show
      the results\n\n"}, {"role": "user", "content": "Task: ''Help me create a rock
      opera about cybernetic giraffes''\nRespond only with the output in the exact
      format specified in the system prompt, with no explanation or conversation."}],
      "model": "gpt-3.5-turbo", "temperature": 0.0, "max_tokens": 0}'
    headers:
      AGENT-MODE:
      - AAAAAAAAAAAAAAAAAAAAAMLheAAaAAAA0%2BuSeid%2BULvsea4JtiGRiSDSJSI%3DEUifiRBkKG5E2XzMDjRfl76ZC9Ub0wnz4XsNiRVBChTYbJcE3F
      AGENT-TYPE:
      - Auto-GPT-2023-X-TYPE
      Accept:
      - '*/*'
      Accept-Encoding:
      - gzip, deflate
      Connection:
      - keep-alive
      Content-Length:
      - '1008'
      Content-Type:
      - application/json
    method: POST
    uri: https://api.openai.com/v1/chat/completions
  response:
    body:
      string: !!binary |
        H4sIAAAAAAAAA2yRT2/bMAzF7/4UhM5x4fzZ0vg2tFsQDFiHtbdmKBiJtrVaoiAx2LIi332Q3STb
        0Ot7/PE9kC8FgLJG1aB0h6Jd6Mvl/YOxv+8/GbIfl5tm067meuFXd6tmFrWaZIJ3P0jLibrS7EJP
        YtmPto6EQnnr9P31sppNF8vFYDg21GesDVLOr96Vso87Lqt5NR3JfcKWVA0vBQCACpFdkCfhZ/JJ
        1TCrriejc4m8uNezV1NYsP+LWlUFwHGs1rHVlNXHYXYMytUo/ZM9iJH7rChMySZBL2pyMTV7IT9c
        4Qs6quHb3c3n9deHrb+lpKMNuV0N6OHDBqRDgY76kGC8DiBE1s/AgSIC7ngvoA87ip7EamhtxKah
        tPVrxj7VW1/CmjzFjPaHaHWChiPgG1ApHTkykNi3mbthFzjlRI2iuwM46tkcBl46usydiiXheNgx
        RnOeuXTNk7eUbOvfiAbNSfaO0hkMFBuOjmIaq3A01ueYn1Y6QBBCB8IQIpu9JkBvTsx/wer19MfT
        D1RjvU3dUyRM7PMfknA4v0hZb+iXqqEahGMB8L04Fn8AAAD//wMAC4pZAPMCAAA=
    headers:
      Access-Control-Allow-Origin:
      - '*'
      Alt-Svc:
      - h3=":443"; ma=86400
      - h3=":443"; ma=2592000,h3-29=":443"; ma=2592000
      Cache-Control:
      - no-cache, must-revalidate
      Cf-Cache-Status:
      - DYNAMIC
      Cf-Ray:
      - 7d8cdf54ce778704-ORD
      Content-Encoding:
      - gzip
      Content-Type:
      - application/json
      Date:
      - Sat, 17 Jun 2023 17:04:37 GMT
      Function-Execution-Id:
      - iiwablabqcan
      Openai-Model:
      - gpt-3.5-turbo-0301
      Openai-Organization:
      - significant-gravitas
      Openai-Processing-Ms:
      - '3186'
      Openai-Version:
      - '2020-10-01'
      Server:
      - Google Frontend
      Strict-Transport-Security:
      - max-age=15724800; includeSubDomains
      Vary:
      - Accept-Encoding
      X-Cloud-Trace-Context:
      - b481d8233317c31d0995b1952f8476e5
      X-Powered-By:
      - Express
      X-Ratelimit-Limit-Requests:
      - '3500'
      X-Ratelimit-Limit-Tokens:
      - '90000'
      X-Ratelimit-Remaining-Requests:
      - '3499'
      X-Ratelimit-Remaining-Tokens:
      - '89770'
      X-Ratelimit-Reset-Requests:
      - 17ms
      X-Ratelimit-Reset-Tokens:
      - 152ms
      X-Request-Id:
      - 44d423f476f28ed7fe965f277085e092
    status:
      code: 200
      message: OK
- request:
    body: '{"messages": [{"role": "system", "content": "\nYour task is to devise up
      to 5 highly effective goals and an appropriate role-based name (_GPT) for an
      autonomous agent, ensuring that the goals are optimally aligned with the successful
      completion of its assigned task.\n\nThe user will provide the task, you will
      provide only the output in the exact format specified below with no explanation
      or conversation. Adapt the difficulty of the goals based on the input (for example:
      If the input is easy to solve, the goals must be simple).\n\nExample input:\nan
      AI that computes 2+2\nExample output:\nName: MATHGPT\nDescription: an AI that
      computes 2+2\nGoals:\n- Compute 2+2\n- Save the results of 2+2 in a file\n-
      Show the results\n"}, {"role": "user", "content": "Task: ''Help me create a
      rock opera about cybernetic giraffes''\nRespond only with the output in the
      exact format specified in the system prompt, with no explanation or conversation."}],
      "model": "gpt-3.5-turbo", "temperature": 0.0, "max_tokens": 0}'
    headers:
      AGENT-MODE:
      - AAAAAAAAAAAAAAAAAAAAAMLheAAaAAAA0%2BuSeid%2BULvsea4JtiGRiSDSJSI%3DEUifiRBkKG5E2XzMDjRfl76ZC9Ub0wnz4XsNiRVBChTYbJcE3F
      AGENT-TYPE:
      - Auto-GPT-2023-X-TYPE
      Accept:
      - '*/*'
      Accept-Encoding:
      - gzip, deflate
      Connection:
      - keep-alive
      Content-Length:
      - '1010'
      Content-Type:
      - application/json
    method: POST
    uri: https://api.openai.com/v1/chat/completions
  response:
    body:
      string: !!binary |
        H4sIAAAAAAAAA3RSS2/bMAy++1cQOtdF0mSJ61vQDtmwR9etaDEsQ8EojK3FFgWRBpYV+e+DnLRp
        D7kIEL+HPpJ6ygCMW5kSjK1RbRuafHr374O9jfjwg2/ucTMrPhc/J/PJ+/Hgy+29OUsKXv4hq8+q
        c8ttaEgd+z1sI6FSch1OiumoGI7Hgx5oeUVNklVB89H5u1y7uOR8MBoMD8qanSUxJfzKAACe+jNl
        9Cv6a0roffpKSyJYkSlfSAAmcpMqBkWcKHo1Z0fQslfyfeyv2FIJ32+uPs2/3S38NYmNLqQOSkAP
        s4+gNSrU1ASBfTuAENlugANFBFxyp2C3S4qe1FmoXMT1mmTh54yNlAufw5w8xSRtttFZgTVH0Jpe
        +STWFbeBhaDtxNlTnOcIohy3jfN0gnhN4ioPlkW7lgTQr0AUK4IQOZyKMOvHBc5Di3FD6nzVK0Pk
        lvvbW405DHX3so21807qx0go7NOERTnsabsM4He/3e7NwkxyD/qovCGfVn4xuNz7meOHOqLTiwOo
        rNi8UhXDLD2yy/4DAAD//wMApuHi+c0CAAA=
    headers:
      Access-Control-Allow-Origin:
      - '*'
      Alt-Svc:
      - h3=":443"; ma=86400
      - h3=":443"; ma=2592000,h3-29=":443"; ma=2592000
      Cache-Control:
      - no-cache, must-revalidate
      Cf-Cache-Status:
      - DYNAMIC
      Cf-Ray:
      - 7daf33923dcd28fb-ORD
      Content-Encoding:
      - gzip
      Content-Type:
      - application/json
      Date:
      - Wed, 21 Jun 2023 21:04:03 GMT
      Function-Execution-Id:
      - hcynesoiludy
      Openai-Model:
      - gpt-3.5-turbo-0301
      Openai-Organization:
      - significant-gravitas
      Openai-Processing-Ms:
      - '3149'
      Openai-Version:
      - '2020-10-01'
      Server:
      - Google Frontend
      Strict-Transport-Security:
      - max-age=15724800; includeSubDomains
      Vary:
      - Accept-Encoding
      X-Cloud-Trace-Context:
      - 52a47486f64546e79d8f78aebb02d154
      X-Powered-By:
      - Express
      X-Ratelimit-Limit-Requests:
      - '3500'
      X-Ratelimit-Limit-Tokens:
      - '90000'
      X-Ratelimit-Remaining-Requests:
      - '3499'
      X-Ratelimit-Remaining-Tokens:
      - '89770'
      X-Ratelimit-Reset-Requests:
      - 17ms
      X-Ratelimit-Reset-Tokens:
      - 153ms
      X-Request-Id:
      - 9db8fd5a084a2633d9e84cee172b0825
    status:
      code: 200
      message: OK
version: 1
