interactions:
- request:
    body: '{"model": "gpt-3.5-turbo", "messages": [{"role": "system", "content": "\nYour
      task is to devise up to 5 highly effective goals and an appropriate role-based
      name (_GPT) for an autonomous agent, ensuring that the goals are optimally aligned
      with the successful completion of its assigned task.\n\nThe user will provide
      the task, you will provide only the output in the exact format specified below
      with no explanation or conversation.\n\nExample input:\nHelp me with marketing
      my business\n\nExample output:\nName: CMOGPT\nDescription: a professional digital
      marketer AI that assists Solopreneurs in growing their businesses by providing
      world-class expertise in solving marketing problems for SaaS, content products,
      agencies, and more.\nGoals:\n- Engage in effective problem-solving, prioritization,
      planning, and supporting execution to address your marketing needs as your virtual
      Chief Marketing Officer.\n\n- Provide specific, actionable, and concise advice
      to help you make informed decisions without the use of platitudes or overly
      wordy explanations.\n\n- Identify and prioritize quick wins and cost-effective
      campaigns that maximize results with minimal time and budget investment.\n\n-
      Proactively take the lead in guiding you and offering suggestions when faced
      with unclear information or uncertainty to ensure your marketing strategy remains
      on track.\n"}, {"role": "user", "content": "Task: ''scan the internet for new
      python code''\nRespond only with the output in the exact format specified in
      the system prompt, with no explanation or conversation."}], "temperature": 0.5,
      "max_tokens": 0}'
    headers:
      Accept:
      - '*/*'
      Accept-Encoding:
      - gzip, deflate
      Connection:
      - keep-alive
      Content-Length:
      - '1607'
      Content-Type:
      - application/json
    method: POST
    uri: https://api.openai.com/v1/chat/completions
  response:
    body:
      string: !!binary |
        H4sIAAAAAAAAA2SUTW8bOQyG7/4VxJztIEnz0fpWdIGkPbTpdve0WRS0xJnhWkNOJcqOW+S/L6SZ
        2BvslRTFlw9f6dcCoGHfrKFxPZobxrC6/frxdsvdp8MV+fub+4+f3z19vf9kT+n92GGzLBW6+Yec
        vVSdOR3GQMYqU9pFQqNy68XN25vr8/Pr68uaGNRTKGXdaKs3Z9cry3Gjq/M35xdTZU7YUbOGXwsA
        gGaMOoz23XRLkpo1XN6+XU6ZU8tT9uLd1Zw1NQynxNXt5QLgedLWKzsq0b/q2alT0UbpVfMajBpK
        pMGUOBmKNctT0qkYScXwGQdaw8Phm0O5e/jjUX6j5CKPReAaUACzqeigOQF2JAbWo0FymmMC6wlY
        jKKQQauxBgIaJQMUD4Mmg0iBdigGDwfrVcCpJzCFLdEInnYUdKSYII8r05VHI9iz9f+9yyKJT/XK
        MaKzAuLsUe4UQ1o/ygo+qBhL1pzCAQYVNo2AsGdPEFE6Am1BJbAQJM3RUVoCiwvZs3Rwx3afN0v4
        Zui28GVHsQ26X9aGv5P3bMuimD2JcXsAof3raQoTTqdRTeGgOU5wKFlRW3T+mQjQ71AceRC0HDFA
        QOkydgRjVEcpFUWVHrq+CA6EUUrQyPXCPzKl0qDlYBRBs0HQ/epHxsB2AI3A8Sikypu4sUY2/kkV
        bN1MTtTmUNMsrcYBjXcEkWZEs+iHqLsC0qk4TvS/8ykPA0amVCAXNMemPXd94K432NIBWioDF/Ib
        EmrZ0kR41OJGxgA+4n6Dblvn6ymMhSIMuKW5IXnw5DixSgLclNn3PVlPsVSg19EKAPQ4Wp2zSJnH
        +NK2FKFYTQUD/yQPkZwOA4lHqzduMJEHlWl5aSTHLbvTFpcwRmopklQDVfGYDDbU4461iiBJOc6W
        KOojOSqUjtSPuynlOwwZN4FOQFVmva88XT1QK+bZZoMJ0fFhHJWB7goQHmgJudqpJfIFbD2plVfi
        TjBU0jyMUWeJszo3LXByiFCqu30BOvvdXh5EWX05fcSZzpr5t3l++XaaloVT/z0SJpXy9STT8fgr
        NSyenpo1nNfA8wLg78Xz4l8AAAD//wMAuXtgFecFAAA=
    headers:
      CF-Cache-Status:
      - DYNAMIC
      CF-RAY:
      - 7d5b31859b700bdc-AMS
      Cache-Control:
      - no-cache, must-revalidate
      Connection:
      - keep-alive
      Content-Encoding:
      - gzip
      Content-Type:
      - application/json
      Date:
      - Sun, 11 Jun 2023 16:22:39 GMT
      Server:
      - cloudflare
      access-control-allow-origin:
      - '*'
      alt-svc:
      - h3=":443"; ma=86400
      openai-model:
      - gpt-3.5-turbo-0301
      openai-organization:
      - user-bu4se1016cknrpfpkym4vvvg
      openai-processing-ms:
      - '7090'
      openai-version:
      - '2020-10-01'
      strict-transport-security:
      - max-age=15724800; includeSubDomains
      x-ratelimit-limit-requests:
      - '3500'
      x-ratelimit-limit-tokens:
      - '90000'
      x-ratelimit-remaining-requests:
      - '3499'
      x-ratelimit-remaining-tokens:
      - '89622'
      x-ratelimit-reset-requests:
      - 17ms
      x-ratelimit-reset-tokens:
      - 252ms
      x-request-id:
      - b40de1e52fcc42b6c40f8c45336f52b0
    status:
      code: 200
      message: OK
version: 1
